### PR TITLE
Use the latest version of boot

### PR DESCRIPTION
**Pull request by benzen**
Copied from https://github.com/pandeiro/heroku-buildpack-boot/blob/master/bin/compile#L45-l50

### CODE REVIEW

**Comment by paxan** [comment]
@benzen thanks for this. I'd prefer that the version of `boot.sh` is pinned. To avoid potential regressions.

OTOH, sounds like `boot.sh` v2.0.0 started to have some sort of bootstrapping issue #3, which might have been mitigated if we always grabbed the latest `boot.sh`

**Comment by benzen** [comment]
I understand why you choose this.
But since boot os 2.2.0 this doesn t work. To keep it working you must download the latest version of boot.sh

Envoyé de mon iPhone

**Comment by jkutner** [comment]
I would recommend keeping the boot version pinned, and proactively upgrading it when Boot releases new versions. The advantage of pinning it is that it's predictable. It also allows someone to use an other version of the buildpack (and thus Boot) by specifying a URL:

```
$ heroku buildpacks:set https://github.com/upworthy/heroku-buildpack-boot#some-tag
```

So maybe, upgrading boot regularly and tagging each time is best?

Also, you can still set `BOOT_VERSION` to run with a different core version. The version of the `boot.sh` script is the version of the "launcher".

**EDIT**
BTW, I maintain the [Heroku Clojure buildpack](https://github.com/heroku/heroku-buildpack-clojure), so I'm speaking from experience :)

**Comment by benzen** [comment]
It sound's like a good idea.
The version of launch is not always important but it happend that there is
breaking change when using the 2.0 launcher and the latest boot.

Maybe we need to make it a constant at the top of the file, so that's it
much more clear what and why is version is picked up, also it should
simplify the update path.

2015-09-01 10:51 GMT-04:00 Joe Kutner notifications@github.com:

> I would recommend keeping the boot version pinned, and proactively
> upgrading it when Boot releases new versions. The advantage of pinning it
> is that it's predictable. It also allows someone to use an other version of
> the buildpack (and thus Boot) by specifying a URL:
> 
> $ heroku buildpacks:set https://github.com/upworthy/heroku-buildpack-boot#some-tag
> 
> So maybe, upgrading boot regularly and tagging each time is best?
> 
> Also, you can still set BOOT_VERSION to run with a different core
> version. The version of the boot.sh script is the version of the
> "launcher".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/upworthy/heroku-buildpack-boot/pull/4#issuecomment-136749831
> .

## 

Benjamin DREUX

**Comment by jkutner** [comment]
@benzen so make it configurable but static? something like `BOOT_SH_VERSION=${BOOT_SH_VERSION:-"2.2.0"}`? That seems like a good idea to me.

**Comment by paxan** [comment]
:+1: 
I agree that we should introduce `BOOT_SH_VERSION` that is an implicitly allowed config var that may be passed via Heroku config. It should default to some current version (e.g. `2.2.0`, which will be proactively updated from time to time as @jkutner suggests).

**Comment by paxan** [comment]
See #8

**Pull request closed without merging**
